### PR TITLE
Little changes to prevent unnecessary sending the 'UIControlEventValueChanged'

### PR DESCRIPTION
**Pull request by shc-vj**
Useful especially when using the slider as the media control

### CODE REVIEW

**Comment by cbpowell** [comment]
Did you end up finding this change unnecessary? I hadn't yet had a chance to look at it.

**Comment by shc-vj** [comment]
Hi !  I slightly change my approach :)
Before i will send you a pull request, tell me if using KVC to set a originally read-only property is OK for you?
I did get rid of 'isSliding' property and use original 'isTracking', but this demand to set 'isTracking' in 'endTrackingWithTouch:withEvent:' which is read-only property (i used simply KVC  [self setValue:@(NO) forKey:@"tracking"]). Might it be a violation of Apple App Store rules?
Originally this is responsibility of [UISlider endTrackingWithTouch:withEvent:] to set 'isTracking' to NO, but original implementation interfere with this solution.

**Comment by cbpowell** [comment]
Unfortunately I don't think that's an approach I'd like to take! I'd like to avoid messing with internals like that, as like you said it could possibly get an app rejected.

The standard UISlider sends a `UIControlEventValueChanged` action on `endTrackingWithTouch:`, so I wouldn't want to silence that. Perhaps you could handle the issues you're seeing by comparing the new value to a stored, previous value in your view controller, and ignore it if there's no change?

There is also a [known bug](http://stackoverflow.com/questions/20903317/uislider-behaviour-in-ios7-versus-ios6) in UISlider (it doesn't seem to be fixed in iOS 8+, either) where the slider will "jump" when the user first touches it. I'm not sure if the suggested fix of adding a custom knob image fixes the issue with CPSlider, but I suspect it might. This one could be tougher to get around, but you could possibly add some logic to ignore the jump by requiring the value to change by some threshold (on the first value change only).

**Comment by shc-vj** [comment]
Ok, no messing with internals. Simply 'overriding' the `tracking` property works pretty well, a lot of code checks slider `.isTracking` property in its `UIControlEventValueChanged` hadler, so proper value of this property is neccessary to  be a *drop-in* replacement to the `UISlider`.

According to [bug](http://stackoverflow.com/questions/20903317/uislider-behaviour-in-ios7-versus-ios6):
- setting the custom thumb image work pretty well, indeed
- without the custom thumb image, not calling a `super` at all works and we avoid sending `UIControlEventValueChanged` twice (`[UISlider beginTrackingWithTouch:withEvent:` also send `UIControlEventValueChanged`) - first with improper value as a result of calling to `super` and second corrected with fix.
Calling `super` is a probably far more compatible with future updates, but as for now receiving a improper value is not very nice :(

**Pull request closed without merging**
